### ISSUE TITLE
Create Sample Repo

### ISSUE THREAD

**Issue by theja0473** [theja0473/C-Programming#4]
Sample C Programming Build using make file

**Comment by denglitong** [comment]
@theja0473 hello，nice to meet you! maybe here is not the place to talk about this, but i really want to contact with you, i encounter a problem nobody else can help but except you! i would appreciate much about your effort to help me! here is how it goes:
To be straghtforward, i need you to delete the project https://github.com/theja0473/gocoverity which forked from mine(which has be deleted). the reason is that it contains an invalid inner account of my company due to my mistake, and it was caught by my company security team and the fork repo is expected to be deleted. so would you please help me to get it done? I would appreciate much and thank you very much! expected to hear from you, my dear friend~

**Comment by denglitong** [comment]
hello, can you hear me? best wishes for you in 2021~

**Comment by theja0473** [comment]
> hello, can you hear me? best wishes for you in 2021~

I didn't check this because of I am in COVID Quarantine for couple of months Now I deleted it please enjoy

Sorry for late response!

**Comment by theja0473** [comment]
I think we can close this

**Comment by denglitong** [comment]
God bless you my dear friend, let's fight COVID together!
